version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
      - microservice-network
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
      - microservice-network
    restart: unless-stopped

  config-server-ms:
    image: matthewoduamafu/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    depends_on:
      - serviceregistry
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  serviceregistry:
    image: matthewoduamafu/serviceregistry-ms:latest
    container_name: serviceregistry-ms
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres

  companyms:
    image: matthewoduamafu/companyms:latest
    container_name: companyms
    ports:
      - 8081:8081
    depends_on:
      - serviceregistry
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: matthewoduamafu/jobms:latest
    container_name: jobms
    ports:
      - 8082:8082
    depends_on:
      - serviceregistry
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry-ms:8761/eureka

  reviewms:
    image: matthewoduamafu/reviewms:latest
    container_name: reviewms
    ports:
      - 8083:8083
    depends_on:
      - serviceregistry
      - postgres
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-ms:
    image: matthewoduamafu/gateway-ms:latest
    container_name: gateway-ms
    ports:
      - 8084:8084
    depends_on:
      - serviceregistry
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - postgres

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
